# Generated by Django 4.2.4 on 2023-11-04 16:50

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermessages', '0004_alter_thread_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='updated',
        ),
        migrations.AddField(
            model_name='thread',
            name='When Created',
            field=models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
