# Generated by Django 4.2.4 on 2023-11-04 16:56

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermessages', '0006_remove_thread_when_created_thread_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 22, 26, 2, 684108), verbose_name=django.contrib.auth.models.User),
        ),
    ]
