# Generated by Django 4.2.4 on 2023-11-04 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermessages', '0010_alter_thread_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 22, 52, 14, 958108)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 22, 52, 14, 957108)),
        ),
        migrations.AlterField(
            model_name='thread',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 22, 52, 14, 957108)),
        ),
    ]
